mediainfo.exe --Inform=file://template.txt "P:\_MKV\_Couples Retreat (2009) (4.32G)\Couples.Retreat.2009.720p.BluRay.x264.DTS-WiKi.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_Sans sous titres\Beyond Reasonable Doubt (4.37G)\bard720p-profile.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_Sans sous titres\Bright Star (2009) (8.74G)\Bright.Star.2009.LiMiTED.1080p.BluRay.x264-CiNEFiLE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_Sans sous titres\Circle of Pain (2010) (4.35G)\Circle of Pain (2010).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_Sans sous titres\Nobel Son (4.37G)\Nobel Son.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_Sans sous titres\Rebound, The (4.38G)\The Rebound.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_Sans sous titres\Red Road (7.95G)\Red Road.1080p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_Sans sous titres\Road of No Return (4.37G)\lchd-ronr.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_Sans sous titres\Road of No Return (4.37G)\Road of no Return.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_Sans sous titres\Wag the dog (1997) (4.1G)\Wag The Dog 1997 HDTV 720p x264 AC3 - fulltime.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_Unthinkable (2010) (4.37G)\Unthinkable (2010).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\12 Rounds (4.37G)\12 Rounds.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\2 Fast 2 Furious (12.32G)\2 Fast 2 Furious 2003 1080p BluRay DTS x264-DON.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\3 10 to Yuma (2007) (1.43G)\3.10.To.Yuma.m-HD.x264-vaLk.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Accident (4.37G)\Accident.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Admiral (2008) (6.54G)\Admiral.2008.720p.BluRay.DTS.x264-ESiR.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Alatriste (6.56G)\Alatriste.x264.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Ali (2001) (7.94G)\Ali.2001.720p.BluRay.DTS.x264-DON.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Alice (2009) (8.75G)\Alice.2009.720p.Bluray.X264-DIMENSION.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Alice in Wonderland (2010) (7.95G)\cbgb-alicewonderland1080.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\All about Steve (2009) (4.37G)\All about Steve.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\American Gangster (2007) (2.8G)\American Gangster (2007).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Analyse That (2002) (4.37G)\Analyze.That.2002.720p.Bluray.X264-DIMENSION.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Analyse This (1999) (4.37G)\Analyze.This.1999.720p.Bluray.X264-DIMENSION.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Anger Management (2003) (1.37G)\Anger.Management[2003]m-HD.x264-11x3.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Arlington Road (1999) (6.56G)\Arlington Road 1999 720p BluRay x264-REVEiLLE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Armored (4.37G)\Armored.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Back to the Future I (1985) (4.37G)\Back.to.the.Future.1985.720p.HDTV.x264-ESiR.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Back to the Future II (1989) (4.38G)\Back.to.the.Future.Part.II.1989.720p.HDTV.x264-ESiR.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Back to the Future III (1990) (4.38G)\Back.to.the.Future.Part.III.1990.720p.HDTV.x264-ESiR.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Bagdad Cafe (4.37G)\Bagdad.Cafe.1987.720p.BluRay.x264-CiNEFiLE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Bandidas (4.37G)\Bandidas.2006.720p.BluRay.x264-CiNEFiLE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Bank Job, The (2008) (1.07G)\The.Bank.Job.2008.m-HD.x264-AsCo.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Beyond Borders (4.37G)\Beyond Borders.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Big Daddy (1999) (4.37G)\big.daddy.1999.720p.bluray.x264-amiable.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Big Hit, The (1998) (4.37G)\The.Big.Hit.1998.720p.BluRay.AC3.x264.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Black Rain (1989) (5.87G)\BlackRain_BD.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Blade  (1998) (6.56G)\Blade.1998.720p.BluRay.x264-CiNEFiLE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Blade 2 (1998) (6.56G)\hdc-blade2-720.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Blade 3 (2004) (4.37G)\hdc-blade3-720.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Blue Streak (4.37G)\Blue.Streak.1999.720p.BluRay.DTS.x264-iLL.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Body of Lies (2008) (4.37G)\Body of Lies.720P.septic.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Bottle Rocket (4.37G)\Bottle.Rocket.1996.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Bounty Hunter, The (2010) (4.37G)\The.Bounty.Hunter.2010.720P.BRRip.x264..mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Bride Wars (4.36G)\Bride Wars.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Brooklyns Finest (2010) (4.36G)\Brooklyns Finest (2010).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Bruce Almighty (2003) (2.5G)\Bruce.Almighty.2003.720p.m-HD.AC3.x264-ortamci.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Burn after Reading (2009) (7.95G)\Burn after Reading 1080p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Butterfly On A Wheel (2007) (8.36G)\B.O.A.W-EuReKA.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Cars (2006) (1.94G)\Cars.2006.m-720p.AC3.x264~RKO.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Cash (4.37G)\cash.2010.720p.bluray.x264-thugline.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Casino (1995) (8.76G)\mhq-casino.1995.720p.x264.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Castaway (7.9G)\Cast.Away.2000.720p.BluRay.DTS.x264-ESiR.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Cell, The (2000) (4.35G)\The.Cell.2000.720p.BD.DTS.x264-DON.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Centurion (2010) (4.37G)\Centurion.2010.Limited.720p.BRRip.x264-HDLiTE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Chain Reaction (1996) (8.9G)\ChainReaction.1996.DTS.1080p.BluRay.x264.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Changing Lanes (4.37G)\Changing.Lanes.2002.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Charlie's Angels (2000) (4.36G)\m-cangels-720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Chasing Amy (1997) (4.37G)\metis-ca-bd720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Chloe (8.49G)\Chloe 2009 1080p BluRay DTS x264-DNL.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\City of Ember (4.36G)\City.Of.Ember.2008.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Clash of the Titans (2010) (4.37G)\Clash of the Titans (2010).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Cobra (1986) (3.87G)\Cobra.1986.AC3.E.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Cocoon (8.09G)\Cocoon.1985.German.AC3D.DL.1080p.BluRay.x264-HDA.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Cold Souls (2009) (4.64G)\Zamershie.dushi.2009.x264.BDRip.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Collateral Damage (4.37G)\Collataral Damage.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Coming to America (4.37G)\coming.to.america.1988.dvd5.720p.hddvd.x264-reveille.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Commando (1985) (4.35G)\Commando.1985.720p.BluRay.x264-SEPTiC.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Contract, The (6.54G)\The.Contract.2006.Bluray.720p.DualAudio.x264-CHD.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Cop Out (2010) (4.37G)\Cop Out (2010).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Count of Monte Cristo, The (2002) (5.47G)\The.Count.of.Monte.Cristo.2002.720p.BluRay.X264-AMIABLE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Crazies, the (2010) (4.37G)\The Crazies (2010).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Crazy Heart (2009) (10.15G)\Crazy.Heart.2009.1080p.BluRay.x264.DTS-WiKi.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Crouching Tiger, Hidden Dragon (2000) (3.15G)\Crouching.Tiger.Hidden.Dragon.2000.m-720p.x264-copasetic.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Curious Case of Benjamin Button, the (7.37G)\The Curious Case of Benjamin Button.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Da Vinci Code, the (6.56G)\The Da Vinci Code.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Danny the Dog (2005) (1.87G)\Danny the Dog (2005) .mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Date Night (2010) (4.36G)\Date Night(2010).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Day After Tomorrow, The (9.25G)\tl-the.day.after.tomorrow.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Daybreakers (2009) (4.32G)\Daybreakers.2009.720p.BluRay.x264.DTS-WiKi.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Dead Man Running (2009) (4.37G)\haideaf-dmr.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Dead Presidents (4.37G)\Dead Presidents.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Death Race (4.35G)\deathrace-septic.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Deep Impact (1998) (4.37G)\hdc-deepimpact-720.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Defiance (6.53G)\Defiance.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Did you hear about the Morgans (2010) (4.37G)\m-dyhatm-720.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Dogma (4.37G)\Dogma.720P.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Donnie Darko Directors Cut (2001) (11.17G)\Donnie.Darko.DC.2001.1080p.BluRay.x264.DTS5.1-CtrlHD.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Dorian Gray (2009) (4.37G)\Dorian.Gray.2009.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Driven to Kill (4.37G)\Driven to Kill.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Drop Zone (1994) (4.37G)\melite-dropzone-720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Edge of Darkness (2010) (6.56G)\hubris-eod.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Edge of Love, The (2008) (4.37G)\The.Edge.Of.Love.2008.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Elsewhere (7.96G)\adr-ew.1080p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Exam (2009) (4.36G)\Exam (2009).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Extract (2009) (4.37G)\cbgb-extract.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Fargo 720 (4.35G)\Fargo.1996.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Few Good Men, A (1992) (7.96G)\A.Few.Good.Men.1992.Bluray.720p.x264.DTS-WiKi.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Final Destination, the (2009) (4.37G)\The.Final.Destination.2009.720p.BluRay.x264.DTS-WiKi.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Firewall (2006) (7.3G)\Firewall.2006.BluRay.1080p.AC3.x264.dxva-EuReKA.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Firm, The (1993) (6.63G)\The.Firm.1993.720p.HDTV.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Flawless (2007) (4.37G)\Flawless.2007.720p.Bluray.X264-DIMENSION.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Forrest Gump (4.28G)\Forrest Gump.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Fracture (2007) (11.19G)\Fracture.2007.BluRay.1080p.DTS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Franklyn (2008) (4.37G)\Franklyn.2008.limited.720p.bd.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Frequency (2000) (4.37G)\Frequency.2000.720p.HDTV.x264-MCR.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\From Paris With Love (2010) (4.37G)\From Paris With Love (2010).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Funny People (7.95G)\Funny.People.Unrated.2009.720p.Bluray.x264.DTS-WiKi.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\G.I. Joe - The Rise of Cobra (2009) (7.96G)\G.I.Joe.The.Rise.Of.Cobra.2009.720p.BluRay.DTS.x264-CtrlHD.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Galaxy.Quest.1999.720p.Bluray.X264-DIMENSION\Galaxy.Quest.1999.720p.Bluray.X264-DIMENSION.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Galaxy.Quest.1999.720p.Bluray.X264-DIMENSION\Sample\galaxy.quest.bluray-dimension.sample.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Gattaca (1997) (9G)\Gattaca.1997.1080p.BluRay.DTS.x264-NLsub.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Godfather ,The (1972) (4.37G)\Godfather ,The (1972).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Godfather 2,The (1974) (4.37G)\Godfather 2,The (1974).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Godfather 3,The (1990) (4.37G)\Godfather 3,The (1990).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Great Buck Howard, the (2008) (4.37G)\The.Great.Buck.Howard.2008.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Green Zone (2010) (6.56G)\cbgb-greenzone720.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Grown Ups (2010) (5G)\Grown.Ups.2010.Bluray.720p.DTS.x264-CHD.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Harry Brown (2009) (7.94G)\harry.brown.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Harsch Times (7.92G)\Harsh Times 2005 1080p BluRay DTS x264-iLL.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Heat (1995) (6.56G)\hdc-heat-720.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\High Crimes (7.94G)\High Crimes.1080p..mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Hoax, The (2006) (10.31G)\das.howard.hughes.komplot.1080p.DualAudio.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Home Alone 2 - New York (6.56G)\Home.Alone.2.Lost.In.New.York.SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Hostage (4.37G)\reveille-hostage-x264.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\House of Flying Daggers (2004) (6.34G)\House of flying drager 2004.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\How to lose Friends and Alienate People (2008) (4.37G)\How.To.Lose.Friends.And.Alienate.People.2008.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Howl's Moving Castle (2004) (1.07G)\Howl's.Moving.Castle.2004.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\I Love You Philip Morris (2009) (4.39G)\I Love You Philip Morris.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\In The Line Of Fire (1993) (1.46G)\In.the.Line.of.Fire.1993.m-HD.x264.TheCount.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Incendiary (4.37G)\Incendiary.LIMITED.720p.BluRay.x264-NGR.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Inception (2010) (10.93G)\refined-inception-1080p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Informant, the (2009) (4.37G)\The.Informant!.2009.720p.BluRay.x264-WiKi.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Into The Blue (4.35G)\Into the Blue 05 720p BluRay x264.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Invention of Lying, The (2009) (4.37G)\The.Invention.of.Lying.2009.720p.BluRay.x264.DTS-WiKi.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Ip Man (2008) (4.3G)\Ip Man 2008 720p BluRay DTS x264-CtrlHD.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Iron Man 2 (2010) (5.46G)\exq-iron.man.2-720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\John Q (2002) (2.17G)\John Q (2002) m-720p - AdiT.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Jonah Hex (2010) (4.36G)\Jonah.Hex.2010.Bluray.720p.DTS.x264-CHD.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Jumper (2007) (8.71G)\Jumper.2008.BluRay.1080p.DTS.x264.dxva-EuReKA.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Jurassic Park (1993) (1.43G)\Jurassic Park (1993).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Just Friends (2005) (7.95G)\Just.Friends.2005.1080p.Bluray.X264-DIMENSION.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\K-19 The Widowmaker (6.55G)\K-19.The.Widowmaker.2002.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\King of California, The (4.37G)\King of California.x264.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Knight and Day (2010) (5G)\Knight.and.Day.2010.Bluray.720p.DTS.x264-CHD.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Lakeview Terrace (2008) (4.37G)\Lakeview Terrace.x264-septic.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Last Boyscout, The (1991) (4.37G)\The.Last.Boy.Scout.1991.720p.BluRay.x264-CiNEFiLE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Last Emperor, The (1987) (14.78G)\The Last Emperor 1987 1080p BluRay DTS x264-CtrlHD.DL.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Law Abiding Citizen (2009) (13.19G)\Law.Abiding.Citizen.UNRATED.2009.BluRay.1080p.TrueHD.x264.dxva-FLAWL3SS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Leaving Las Vegas (1995) (9.09G)\Leaving.las.vegas.1080p.Dualaudio.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Legend, The (1993) (4.37G)\Fwint.com.lchd-thelegend.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Lethal Weapon (1987) (4.37G)\Lethal.Weapon.1987.720p.BluRay.x264-ESiR.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Lethal Weapon 2 (1989) (4.37G)\Lethal.Weapon.2.1989.720p.HDDVD.x264-ESiR.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Letters from Iwo Jima (2006) (6.53G)\Letters.from.Iwo.Jima.2006.720p.HDDVD.DTS.x264-ESiR_NL.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Limits of Control, the (2009) (6.56G)\Limits.of.control.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Looking for Eric (6.56G)\Looking.For.Eric.2009.720p.BluRay.x264-CiNEFiLE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Losers, The (2010) (6.56G)\cbgb-losers1080p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Magnum Force (1.43G)\Magnum.Force.1973.m-HD.x264-AsCo.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Man in the Iron Mask, The (6.55G)\The.Man.In.The.Iron.Mask.1998.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Manchurian Candidate, The (2004) (7G)\The.Manchurian.Candidate.2004.720p.HDDVD.x264.DTS-DiR.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Marked for Death (1990) (4.37G)\Marked.For.Death.1990.720p.BluRay.x264-CiNEFiLE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Married to the Mob (1988) (4.37G)\Married.To.The.Mob.1988.720p.HDTV.x264-RuDE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Mask of Zorro, The (1998) (6.56G)\The.Mask.Of.Zorro.1998.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Mask, the (1994) (1.46G)\Mask, The (1994).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Master and Commander (7.92G)\Master.and.Commander.2003.720p.BluRay.DTS.x264-ESiR.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Meet Dave (2008) (1.07G)\Meet.Dave.2008.m-HD.x264-AsCo.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Memento (2000) (8.72G)\Memento.2000.Haiz2.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Memoirs of A Geisha (2005) (4.35G)\Memoirs.of.a.Geisha.2005.720p.BluRay.x264-ESiR.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Men in Black II (2002) (4.37G)\men.in.black.2.2002.720p.hdtv.x264-flatline.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Midnight Run (1988) (7.13G)\Midnight Run720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Misery (7.95G)\Misery.1990.1080p.BluRay.x264-CiNEFiLE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Miss Congeniality (4.37G)\melite-mc1-720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Miss Congeniality 2 (6.56G)\melite-mc2-720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Monsters Ball (2001) (7.94G)\Monsters.Ball.2001.1080p.BluRay.x264-CiNEFiLE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Mr Nobody (2009) (10.93G)\Mr.Nobody.2009.Extended.1080p.BluRay.x264-CiNEFiLE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Murder by numbers (4.37G)\Murder.By.Numbers.2002.720p.HDTV.x264-shon3i.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\My Cousin Vinny (1992) (6.56G)\My.Cousin.Vinny.1992.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\New York I Love You (2009) (4.37G)\New York I love you 2009.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Ninth Gate, The (1999) (6.56G)\The Ninth Gate.BD.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\No Country For Old Men 1080p (2007) (8.74G)\No.Country.for.Old.Men.Blu-Ray.1080p.DTS.x264.dxva-EuReKA.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\No Way Out (1987) (4.37G)\No.Way.Out.1987.720p.HDTV.DD5.1.x264-MX.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\O Brother, Where Art Thou (1.46G)\O.Brother.Where.Art.Thou.2000.m-HD.x264-rodeeoh.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Office Space (4.36G)\Office.Space.1999.720p.BluRay.x264-HANGOVER.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Old Dogs (4.37G)\Old Dogs.720.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Operation Endgame (7.95G)\operation.endgame.2010.1080p.bluray.x264-brmp.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Other Guys, The (2010) (9.06G)\hda-anderecops-1080p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Pale Rider (1985) (4.37G)\Pale.Rider.1985.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Passenger 57 (2.99G)\Passenger.57.1992.720p.HDTV.x264-SiR.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Patriot Games (1992) (4.37G)\Patriot.Games.1992.720p.HDDVD.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Paul Blart Mall Cop (4.37G)\Paul Blart Mall Cop.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Payback Straight Up (2006) (7.95G)\Payback Straight Up 2006 1080p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Police Academy (4.38G)\Police.Academy.1984.x264. HDTVRip.720p.Eng DD.5.1.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Powder Blue (2009) (7.94G)\Powder.Blue.2009.1080p.BluRay.x264-CiNEFiLE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Predator 2 (1990) (4.37G)\Predator.2.1990.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Pride And Prejudice (2005) (1.37G)\Pride.And.Prejudice.2005.MiniHD.x264.NhaNc3.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Prince of Persia - The Sands of Time (2010) (13.12G)\Prince.of.Persia.The.Sands.of.Time.2010.1080p.Bluray.x264.DTS-WiKi.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Professionals, The (4.37G)\THe_Professionals.720p.E.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Proposal, The (4.37G)\The Proposal.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Proposition, The (2005) (4.35G)\The.Proposition.2005.720p.BluRay.DTS.x264-ESiR.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Public Enemies (6.56G)\m-pe-720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Punisher War Zone, The (2008) (4.37G)\Punisher.War.Zone.2008.BluRay.720p.DTS.x264.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Quick and the Dead, The (1995) (4.71G)\The.Quick.And.The.Dead.1995.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Rachel is Getting Married (2008) (4.37G)\refined-rachel-blu720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Ransom (1996) (4.36G)\Ransom.720p.x264.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Recruit, the (2003) (9.05G)\The.Recruit.2003.1080p.BluRay.DTS.x264_CZ.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Red Baron, The (2008) (4.95G)\the.red.baron.2008.720p.hddvd.x264-dmr.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Red Heat (1988) (4.38G)\Red.Heat.1988.720p.HDTV.x264-PiGO.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Reign of Fire (2002) (7.95G)\Reign.Of.Fire.2002.1080p.BluRay.x264-CiNEFiLE_www.divxsaati.com.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Repo Men (2010) (8.74G)\repo.men.2010.unrated.1080p.bluray.x264-machd.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Revenge (1990) (4.37G)\Revenge.1990.DC.720p.BluRay.x264-DON.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Road to Perdition (2002) (6.56G)\Road.to.Perdition.2002.720p.Bluray.x264-MELiTE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Road, The (4.37G)\The.Road.2009.720p.BluRay.x264.DTS-WiKi.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Robin Hood (2010) (11.77G)\Robin.Hood.2010.UNRATED.DC.MULTi.1080p.BluRay.x264-AMIABLE-UpByArG.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Salt (2010) (6.54G)\Salt.Director's.Cut.2010.720p.BluRay.DTS.x264.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Shaft 2000 (4.37G)\Shaft.2000.HDTV.720p.x264-H2.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Shining, the (1980) (2.45G)\The.Shining.1980.720p.HDDVD.x264-ESiR.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Shinjuku (2009) (6.5G)\Shinjuku.Incident.2009.BluRay.720p.x264.DTS-WiKi.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Silverado (4.37G)\Silverado.1985.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Sliver (1993) (4.38G)\Sliver.1993.x264.HDTV.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Small Town Secret (8.29G)\Small.Town.Secret.2009.German.AC3D.DL.1080p.BluRay.x264-msd.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Smart.People.1080p (8.19G)\Smart.People.1080p.Dualaudio.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Solaris (2002) (6.5G)\Solaris.2002.HDTV.1080p.x264-SiSL.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Son of Rambow (4.37G)\Son of Rambow.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Sorcerers Apprentice, The (2010) (4.37G)\cbgb-sorcerersapprentice720.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Sphere (1998) (4.37G)\Sphere.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Spy Kids (4.37G)\halcyon-spykids.720p-x264.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Spy Kids 2 (4.37G)\halcyon-spykids2.720p-x264.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Spy Kids 3 (4.37G)\halcyon-spykids3.720p-x264.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Star Trek IX Insurrection (4.37G)\Star.Trek.Insurrection.1998.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Star Trek VIII First Contact (4.37G)\Star.Trek.First.Contact.1996.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Star Trek X Nemesis (4.37G)\Star.Trek.Nemesis.2002.720p.BluRay.x264-SiNNERS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Star wars\Star Wars I - The Phantom Menace (1999) (7.95G)\Star Wars I - The Phantom Menace (1999).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Star wars\Star Wars II - Attack Of The Clone (10.08G)\Star Wars II (2002) 1080p.DTS.5.1AC3 -KrisVB.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Star wars\Star Wars III - Revenge Of The Sith (8G)\Star Wars III (2005) 1080p.5.1AC3 -KrisVB.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Star wars\Star Wars IV - A New Hope (1977) (7.95G)\Star Wars IV - A New Hope (1977).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Star wars\Star Wars V - The Empire Strikes Back (1980) (7.95G)\Star Wars V - The Empire Strikes Back (1980).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Star wars\Star Wars VI - Return Of The Jedi (1983) (7.95G)\Star Wars VI - Return Of The Jedi (1983).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Starship Troopers (7.95G)\Starship.Troopers.1997.720p.BluRay.DTS.x264-ESiR.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Starsky and Hutch (2004) (4.64G)\Starski.i.Hatch.BDRip.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Subway (7.95G)\Subway.1080p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Sudden Impact (1983) (4.85G)\SuddenImpact.BDRip.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Synecdoche New.York (4.37G)\refined-synecdoche-blu720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Tears in The Sun (4.37G)\Tears.of.the.Sun.2003.DVD5.720p.BluRay.x264-CtrlHD.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Terminator Salvation (12.32G)\Terminator.Salvation.2009.Director's.Cut.1080p.BluRay.DTS.x264-WiKi.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\The Book of Eli (2010) (4.37G)\The Book of Eli (2010).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\The Dirty Dozen (10.94G)\The Dirty Dozen 1080p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\The Eagle (25.16G)\The Eagle.1080p.Nlsub.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\The Peacemaker (6.54G)\The.Peacemaker.1997.720p.DTheather.x264-CtrlHD.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\The Quiet American (2002) (6.56G)\The.Quiet.American.2002.1080p.BluRay.X264-AMIABLE.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\The Taking Of Pelham 123 (2009) (4.37G)\The Taking Of Pelham 123 720p BluRay x264 HUBRIS.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Thirst  (2009) (8.74G)\lchd-thirst.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\To Kill a King (2003) (10.55G)\To Kill a King BD DTS 1080p (2003).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Total Recall (1990) (1.43G)\Totall Recall[1990].mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Tropic Thunder (4.08G)\Tropic Thunder.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Twins (1988) (4.37G)\Twins.1988.720p.HDTV.x264-iLL.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Twister (6.56G)\Twister.1996.720p.BluRay.DTS.x264-CtrlHD.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Two for the Money (2005) (4.37G)\two.for.the.money.2005.720p.bluray.x264-hv.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Two Girls and A Guy (4.37G)\Two.Girls.and.a.Guy.1997.720p.Bluray.X264-DIMENSION.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Unforgiven (1992) (2.46G)\Unforgiven (1992).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Universal Soldier Regeneration (4.37G)\Universal.Soldier.Regeneration.2009.720p.Bluray.X264-DIMENSION.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\US Marshals (1998) (4.03G)\US Marshals.1080p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\War (2007) (4.37G)\War.720p.Bluray.x264-SEPTiC.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Wolfman, The (6.56G)\lx-wolfman.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Year One (2009) (4.37G)\inf-yearone.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_VU\Zombieland (2009) (2.15G)\Zombieland (2009) BDRip 720p - Hemanth.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Legends. Live At Montreux. 1997. 720p.DTS x264. TwoDD.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Amy MacDonald - This is The Life (0.05G)\Amy MacDonald - This is The Life [m-720p].mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Backstreet Boys Live (2008) (4.4G)\Backstreet.Boys.Live.From.O2.Arena.2008.HDTV.1080i.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Chris Rea - Farewell tour Road To Hell (2007) (2.94G)\Chris_Rea_ 720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Dave Matthews & Tim Reynolds Live at Radio City (2007) (2.86G)\Dave Matthews and Tim Reynolds - Live at Radio City (2007) [mHD] - LTP.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Deep Purple Live In Montreux (2007) (4.36G)\Deep Purple Live at Montreux.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Dido live at Brixton Academy (2005) (3.43G)\Dido - Live at Brixton Academy.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Elton John - The Red Piano (2005) (4.36G)\Elton John.The Red Piano.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Ennio Morricone Live a Piazza San Marco - Venezia (6.14G)\Ennio Morricone Live a Piazza San Marco - Venezia.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Eric Clapton and Steve Winwood Live from Madison Square Garden (2009) (9.95G)\Eric.Clapton.and.Steve.Winwood.2009.720p.BDRip.HDCLUB.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Hotel California - EAGLES (0.14G)\Hotel California - EAGLES (1080i).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Hotel California - EAGLES (0.14G)\Hotel California.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\John Mayall and the bluesbreakers (2003) (7.92G)\John.Mayall.and.The.Bluesbreakers.2003.70th.Birthday.Concert.720p.BDRip.HDClub.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Kylie Minogue (7.11G)\Kylie Minogue-Kylie X-At o2 Arena 2008 BDRip x264 DTS 720p-DNL.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Lionel Ritchie Live (2007) (6.88G)\Lionel.Ritchie.Live.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Madonna - The Confessions Tour (2006) (1.99G)\MadonnaConfessionsTour  1280x720 x264 DD5.1.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\McCartney Live USA (2006) (7.68G)\Paul.McCartney.The.Space.Within.US.BluRay.720p.x264.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Moby Exit Festival HDTV 720p (0.05G)\moby-exit_festival-hdtv-720p-x264-2009-mv4u.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Moby Exit Festival HDTV 720p (0.05G)\mv4u-moef-sample.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Queen Rock Montreal (1981) (6.53G)\Queen Rock Montreal 1981 720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Red Hot Chili Peppers Live In Milan (2006) (2.36G)\Red.Hot.Chilli.Peppers.Live.in.Milan.720p.x264.AC3-2.0-HDL.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Santana Live in Montreux (2004) (5.97G)\Santana.-.[Live.At.Montreux](BDrip).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Soundstage Presents Seal Live (2008) (4.37G)\sem-spsl.1080p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\The Eagles - Farewell I Tour - Melbourne (2004) (10.89G)\The.Eagles-Farewell.Tour.1.720p.BluRay.DTS.x264-CtrlHD.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\The Police - Live In Concert - Tokyo (2008) (4.37G)\The Police - Live In Concert - Tokyo 2008 - 720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\U2 - Rattle and Hum (1988) (4.35G)\U2.Rattle.and.Hum.1988.DVD5.720p.HDDVD.DTS.x264-CDDHD.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Various Artists - The Strat Pack - Live In Concert (2004) (7.93G)\Various.Artist.-.[The.Strat.Pack.Live.In.Concert.2004].(720p).mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\Within Temptation - Black Symphony Live (2008) (6.56G)\Within Temptation Black Symphony Live.720p.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\ZZ Top - Live from Texas (2008) (4.37G)\Sample.mkv" >> result.csv
mediainfo.exe --Inform=file://template.txt "P:\_MKV\_[MUSIC]\ZZ Top - Live from Texas (2008) (4.37G)\ZZTopTexas2008.mkv" >> result.csv
